name: Build and Deploy the image to DockerHub
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/dvwa
          tags: latest
